### ISSUE TITLE
Setup: Give hint in case of failed COM object registration

### ISSUE THREAD

**Issue by HW71** [HW71/AutoItLibrary#8]
While installing AutoItLibrary on Windows 7 or Windows 10 a DOS console with administration rights is needed in order to register the COM server in Windows.

Currently only a not very useful error message is displayed in case the user tries to install AutoItLibrary without administration rights:

```
Registering COM object using command:
%SYSTEMROOT%\system32\regsvr32.exe /S C:\Python27\Lib\site-packages\AutoItLibrary\lib\AutoItX3_x64.dll
Traceback (most recent call last):
  File "setup.py", line 124, in <module>
    subprocess.check_call(cmd, shell=True)
  File "C:\Python27\lib\subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '%SYSTEMROOT%\system32\regsvr32.exe /S C:\Python27\Lib\site-packages\AutoItLibrary\lib\AutoItX3_x64.dll' returned non-zero exit status 5
```

Of course one could Google for this "non-zero exit status 5" and probably find some additional information regarding "DllRegisterServer failed" - but even then it's a long way to think about missing Admin rights... :-)

Hence an additional hint regarding missing admin rights would be good in case registration failed.

**Comment by HW71** [comment]
With the changes introduced with #9 we now display a hint regarding possibly insufficient rights while trying to register the AutoItX COM server. Of course other problems could be the cause for such a failure so we additionally display the return code + an error message (if present).
